import gyak16

import gyak16


def test_steamdrift_irondale_route():
    assert gyak16.find_routes(gyak16.neighbours, "Steamdrift", "Irondale") == [['Steamdrift', 'Cogburg', 'Copperhold', 'Irondale'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne', 'Irondale'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne', 'Rustport', 'Irondale'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Irondale'], ['Steamdrift', 'Cogburg', 'Irondale'], ['Steamdrift', 'Cogburg', 'Rustport', 'Gizbourne', 'Irondale'], ['Steamdrift', 'Cogburg', 'Rustport', 'Gizbourne', 'Leverstorm', 'Irondale'], ['Steamdrift', 'Cogburg', 'Rustport', 'Gizbourne', 'Leverstorm', 'Copperhold', 'Irondale'], ['Steamdrift', 'Cogburg', 'Rustport', 'Irondale'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Irondale'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne', 'Irondale'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Leverstorm', 'Irondale'], ['Steamdrift', 'Rustport', 'Cogburg', 'Irondale'], ['Steamdrift', 'Rustport', 'Gizbourne', 'Irondale'], ['Steamdrift', 'Rustport', 'Gizbourne', 'Leverstorm', 'Irondale'], ['Steamdrift', 'Rustport', 'Gizbourne', 'Leverstorm', 'Copperhold', 'Irondale'], ['Steamdrift', 'Rustport', 'Gizbourne', 'Leverstorm', 'Copperhold', 'Cogburg', 'Irondale'], ['Steamdrift', 'Rustport', 'Irondale']]


def test_leverstorm_steamdrift_route():
    assert gyak16.find_routes(gyak16.neighbours, "Leverstorm", "Steamdrift") == [['Leverstorm', 'Gizbourne', 'Irondale', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Irondale', 'Cogburg', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Irondale', 'Copperhold', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Irondale', 'Copperhold', 'Cogburg', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Irondale', 'Rustport', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Irondale', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Rustport', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Rustport', 'Irondale', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Rustport', 'Irondale', 'Copperhold', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Gizbourne', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Irondale', 'Gizbourne', 'Rustport', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Irondale', 'Gizbourne', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Irondale', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Irondale', 'Cogburg', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Irondale', 'Copperhold', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Irondale', 'Copperhold', 'Cogburg', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Irondale', 'Rustport', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Irondale', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Irondale', 'Gizbourne', 'Rustport', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Irondale', 'Gizbourne', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Irondale', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Irondale', 'Cogburg', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Irondale', 'Rustport', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Irondale', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Cogburg', 'Irondale', 'Gizbourne', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Cogburg', 'Irondale', 'Rustport', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Cogburg', 'Steamdrift'], ['Leverstorm', 'Copperhold', 'Cogburg', 'Rustport', 'Steamdrift']]

def test_irondale_steamdrift_route():
    assert gyak16.find_routes(gyak16.neighbours, "Irondale", "Steamdrift") == [['Irondale', 'Gizbourne', 'Leverstorm', 'Copperhold', 'Cogburg', 'Steamdrift'], ['Irondale', 'Gizbourne', 'Leverstorm', 'Copperhold', 'Cogburg', 'Rustport', 'Steamdrift'], ['Irondale', 'Gizbourne', 'Rustport', 'Cogburg', 'Steamdrift'], ['Irondale', 'Gizbourne', 'Rustport', 'Steamdrift'], ['Irondale', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne', 'Rustport', 'Steamdrift'], ['Irondale', 'Cogburg', 'Steamdrift'], ['Irondale', 'Cogburg', 'Rustport', 'Steamdrift'], ['Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne', 'Rustport', 'Cogburg', 'Steamdrift'], ['Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne', 'Rustport', 'Steamdrift'], ['Irondale', 'Copperhold', 'Cogburg', 'Steamdrift'], ['Irondale', 'Copperhold', 'Cogburg', 'Rustport', 'Steamdrift'], ['Irondale', 'Leverstorm', 'Gizbourne', 'Rustport', 'Cogburg', 'Steamdrift'], ['Irondale', 'Leverstorm', 'Gizbourne', 'Rustport', 'Steamdrift'], ['Irondale', 'Leverstorm', 'Copperhold', 'Cogburg', 'Steamdrift'], ['Irondale', 'Leverstorm', 'Copperhold', 'Cogburg', 'Rustport', 'Steamdrift'], ['Irondale', 'Rustport', 'Cogburg', 'Steamdrift'], ['Irondale', 'Rustport', 'Gizbourne', 'Leverstorm', 'Copperhold', 'Cogburg', 'Steamdrift'], ['Irondale', 'Rustport', 'Steamdrift']]

def test_cogburg_gizbourne_route():
    assert gyak16.find_routes(gyak16.neighbours, "Cogburg", "Gizbourne") == [['Cogburg', 'Copperhold', 'Irondale', 'Gizbourne'], ['Cogburg', 'Copperhold', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Cogburg', 'Copperhold', 'Irondale', 'Rustport', 'Gizbourne'], ['Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Cogburg', 'Copperhold', 'Leverstorm', 'Irondale', 'Gizbourne'], ['Cogburg', 'Copperhold', 'Leverstorm', 'Irondale', 'Rustport', 'Gizbourne'], ['Cogburg', 'Irondale', 'Gizbourne'], ['Cogburg', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Cogburg', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Cogburg', 'Irondale', 'Rustport', 'Gizbourne'], ['Cogburg', 'Steamdrift', 'Rustport', 'Gizbourne'], ['Cogburg', 'Steamdrift', 'Rustport', 'Irondale', 'Gizbourne'], ['Cogburg', 'Steamdrift', 'Rustport', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Cogburg', 'Steamdrift', 'Rustport', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Cogburg', 'Rustport', 'Gizbourne'], ['Cogburg', 'Rustport', 'Irondale', 'Gizbourne'], ['Cogburg', 'Rustport', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Cogburg', 'Rustport', 'Irondale', 'Leverstorm', 'Gizbourne']]


def test_steamdrift_gizbourne_route():
    assert gyak16.find_routes(gyak16.neighbours, "Steamdrift", "Gizbourne") == [['Steamdrift', 'Cogburg', 'Copperhold', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Irondale', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Irondale', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Irondale', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Rustport', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Rustport', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Rustport', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Leverstorm', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Irondale', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Irondale', 'Leverstorm', 'Gizbourne']]

def test_steamdrift_gizbourne_route_fail():
    assert gyak16.find_routes(gyak16.neighbours, "Steamdrift", "Gizbourne") != [['Steamdrift', 'Cogburg', 'Copperhold', 'Irondale', 'Leverstorm', 'Gizbourne'],['Steamdrift', 'Cogburg', 'Copperhold', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Irondale', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Copperhold', 'Leverstorm', 'Irondale', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Irondale', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Rustport', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Rustport', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Cogburg', 'Rustport', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Copperhold', 'Leverstorm', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Cogburg', 'Irondale', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Irondale', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Irondale', 'Cogburg', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Irondale', 'Copperhold', 'Leverstorm', 'Gizbourne'], ['Steamdrift', 'Rustport', 'Irondale', 'Leverstorm', 'Gizbourne']]


def test_steamdrift_irondale():
    assert (gyak16.map_distance("Steamdrift","Irondale") ==
            "from Steamdrift to Irondale the shortest distance is 2303 km")

def test_leverstorm_steamdrift():
    assert (gyak16.map_distance("Leverstorm","Steamdrift") ==
            "from Leverstorm to Steamdrift the shortest distance is 2885 km")

def test_irondale_steamdrift():
    assert (gyak16.map_distance("Irondale","Steamdrift") ==
            "from Irondale to Steamdrift the shortest distance is 2303 km")

def test_cogburg_gizbourne():
    assert (gyak16.map_distance("Cogburg","Gizbourne") ==
            "from Cogburg to Gizbourne the shortest distance is 1560 km")

def test_steamdrift_gizbourne():
    assert (gyak16.map_distance("Steamdrift","Gizbourne") ==
            "from Steamdrift to Gizbourne the shortest distance is 2829 km")

def test_steamdrift_irondale():
    assert (gyak16.map_distance("Steamdrift","Irondale") ==
            "from Steamdrift to Irondale the shortest distance is 2303 km")